config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show, :destroy]
  # resources :gifs, only: [:show, :index]
  resources :favorite_gifs, only: [:create, :destroy]

  # scope :module => 'admin' do
    resources :categories
    resources :gifs
  # end
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many: gifs
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :favorited, polymorphic: true
end

app/models/gif.rb
class Gif < ActiveRecord::Base
  belongs_to :category
has_many :favorites

  validates :search_terms, presence: true
  validates :url, presence: true, uniqueness: true

end

app/models/user.rb
class User < ActiveRecord::Base
has_secure_password
has_many :favorites
has_many :favorite_gifs, through: :favorites, source: :favorited, source_type: 'Gif'

  validates :username,  presence: true, 
                        uniqueness: true

  enum role: %w(default admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  def require_admin
    render file: "/public/404" unless current_admin?
  end

end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


  def current_admin?
    current_user && current_user.admin?
  end
  
end

app/controllers/favorite_gifs_controller.rb
class FavoriteGifsController < ApplicationController

  before_action :set_project
  
  def create
    if Favorite.create(favorited: @gif, user: current_user)
      redirect_to @gif, notice: 'Gif has been favorited'
    else
      redirect_to @gif, alert: 'Something went wrong.'
    end
  end
  
  def destroy
    Favorite.where(favorited_id: @gif.id, user_id: current_user.id).first.destroy
    redirect_to @gif, notice: 'Gif is no longer in favorites'
  end
  
  private
  
  def set_project
    @gif = Gif.find(params[:gif_id] || params[:id])
  end

end

app/controllers/gifs_controller.rb
require 'gipherator'

class GifsController < ApplicationController
include Gipherator 

def index
  @gifs = Gif.all
end

def new
  @gif = Gif.new
end

def create
  @gif = Gif.new(gif_params)
  find_giphy(@gif)

  if @gif.save
    redirect_to gif_path(@gif)
  else
    render :new
  end
end

def show
  @gif = Gif.find(params[:id])
end

def edit
  @gif = Gif.find(params[:id])
end

def update
  @gif = Gif.find(params[:id])
  if @gif.update(gif_params)
    redirect_to gif_path(@gif)
  else
    render :edit
  end
end

def destroy
  @gif = Gif.find(params[:id])
  @gif.destroy
  redirect_to gifs_path
end

def gif_params
  params.require(:gif).permit(:search_terms, :url)
end


end

app/controllers/gipherator.rb
module Gipherator
attr_reader :new_url

  def find_giphy(gif)
    url_search_terms = gif.search_terms.strip.gsub(" ", "+")
    raw_response = Faraday.get "http://api.giphy.com/v1/gifs/search?q=#{url_search_terms}&api_key=dc6zaTOxFJmzC"
    response = JSON.parse(raw_response.body)
    gif.url = response["data"][0]["embed_url"][5..-1] if response["data"]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
  @user = User.find_by(username: params[:session][:username])
  if @user && @user.authenticate(params[:session][:password])
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  else
    flash.now[:error] = "Unknown user or password."
    render :new
  end
end

def destroy
  session.clear
  redirect_to login_path
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    session[:user_id] = @user.id
    redirect_to user_path(@user)
  else
    flash.now[:error] = "Unknown user or password."
    render :new
  end
end

def show
end

private

def user_params
  params.require(:user).permit(:username, :password)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/categories/index.html.erb
<h1>All Categories</h1>

app/views/gifs/_form.html.erb
<%= form_for @gif do |f| %>
<%= f.text_field :search_terms, placeholder: 'search terms' %>
<%= f.text_field :url, placeholder: 'no url necessary' %>
<%= f.submit "Add Gif" %>
<% end %>

app/views/gifs/edit.html.erb
<h1>Edit Gif:</h1>

<%= render 'form' %>

app/views/gifs/index.html.erb
<div class="jumbotron">
  <div class="container">
  <h1>ALL THE GIFS</h1>
  

  <div class="btn-group">
  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    Categories <span class="caret"></span>
  </button>
  <ul class="dropdown-menu">
    <li><%= link_to "Your Mom", gifs_path %></li>
   <li><%= link_to "Not Your Mom", gifs_path %></li>
   <li><%= link_to "WTF", gifs_path %></li>
  </ul>
</div>


  </div>
</div>

<% @gifs.each do |gif| %>
<div class="col-md-4 well well-lg gif_display">
<h3><%= link_to "#{gif.search_terms}", gif_path(gif) %></h3>
<div class="thumbnail text-center media-middle"><iframe src="<%= gif.url %>" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="http:<%= gif.url %>">via GIPHY</a></p></div>
<% if current_user && current_user.admin? %>
<div class="btn btn-default btn-primary btn-sm pull-right"><%= link_to "Edit Gif", edit_gif_path(gif) %></div>
<div class="btn btn-default btn-danger btn-sm pull-right"><%= link_to "Delete Gif", gif_path(gif), method: :delete %></div>
<% end %>
</div>
<% end %>

app/views/gifs/new.html.erb
<h1>Add a New Gif:</h1>

<%= render 'form' %>

app/views/gifs/show.html.erb
<h1><%= @gif.search_terms %>
	<% gif_id = @gif.id %>
<div>

<iframe src="<%= @gif.url %>" width="480" height="471" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="http:<%= @gif.url %>">via GIPHY</a></p>
<% if current_user && current_user.admin? %>
<div class="btn"><%= link_to "Edit Gif", edit_gif_path(@gif) %></div>
<div class="btn"><%= link_to "Delete Gif", gif_path(@gif), method: :delete %></div>
<% else %>
<% unless current_user.favorite_gifs.exists?(id: gif_id) %>
<div class="btn btn-danger"><%= link_to "<3 Favorite Gif", favorite_gifs_path(gif_id: gif_id), method: :post %></div>
<% else %>
<div class="btn btn-danger"><%= link_to ":( Unfavorite Gif", favorite_gif_path(gif_id), method: :delete %></div>
<% end %>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Gifstragram</title>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	<%= csrf_meta_tags %>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
	<link href="application.css" media="screen" rel="stylesheet">
	<body>
		<div class="navbar topper">
			<div class="navbar-brand"><h1><%= link_to "GIFSTAGRAM", gifs_path %></h1></div>

			
			<% if current_user && current_user.admin? %>
			<div class="navbar-btn btn btn-large btn-primary pull-right">
			<%= link_to "Add a Gif", new_gif_path%></div>
			<div class="navbar-btn btn btn-large btn-primary pull-right">
			<%= link_to "Logout", logout_path, method: :delete %></div>
			<div> Welcome, <%= current_user.username %> </div>
			<% elsif current_user %>
			<div class="navbar-btn btn btn-large btn-primary pull-right">
			<%= link_to "Logout", logout_path, method: :delete %></div>
			<div> Welcome, <%= current_user.username %> </div>
			<% else %>
			<div class="navbar-btn btn btn-large btn-primary pull-right butt"><%= link_to "Login", login_path %></div>
			</div>
			<% end %>


		<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, :id => "flash_#{name}" %>
		<% end %>

		<%= yield %>

	</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>
  <%= form_for(@user) do |f| %>
    <%= f.label "Username" %><%= f.text_field :username %><br>
     <%= f.label "Password" %><%= f.password_field :password %></p>
    <%= f.submit "Create Account" %>
  <% end %>